-- Create pricing table for iPhone battery replacement pricing
CREATE TABLE public.pricing (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  model TEXT NOT NULL,
  price BIGINT NOT NULL,
  original_price BIGINT NOT NULL,
  is_popular BOOLEAN DEFAULT FALSE NOT NULL,
  is_active BOOLEAN DEFAULT TRUE NOT NULL,
  display_order INTEGER DEFAULT 0 NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  CONSTRAINT pricing_pkey PRIMARY KEY (id)
);

-- Enable RLS
ALTER TABLE public.pricing ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Enable read access for all users" ON public.pricing FOR SELECT USING (TRUE);
CREATE POLICY "Enable all access for authenticated users only" ON public.pricing FOR ALL USING (auth.role() = 'authenticated');

-- Insert sample pricing data
INSERT INTO public.pricing (model, price, original_price, is_popular, display_order) VALUES
('iPhone 15 Pro Max', 1200000, 1500000, true, 1),
('iPhone 15 Pro', 1100000, 1400000, false, 2),
('iPhone 15', 900000, 1200000, false, 3),
('iPhone 14 Pro Max', 1000000, 1300000, false, 4),
('iPhone 14 Pro', 900000, 1200000, false, 5),
('iPhone 14', 800000, 1100000, false, 6),
('iPhone 13 Pro Max', 850000, 1100000, false, 7),
('iPhone 13', 700000, 900000, false, 8),
('iPhone 12 Pro Max', 750000, 1000000, false, 9),
('iPhone 12', 650000, 850000, false, 10),
('iPhone 11 Pro Max', 700000, 900000, false, 11),
('iPhone 11', 600000, 800000, false, 12),
('iPhone XS Max', 650000, 850000, false, 13),
('iPhone XS/XR', 600000, 800000, false, 14),
('iPhone X', 550000, 750000, false, 15),
('iPhone 8 Plus', 500000, 700000, false, 16),
('iPhone 8', 450000, 650000, false, 17),
('iPhone 7 Plus', 400000, 600000, false, 18),
('iPhone 7', 350000, 550000, false, 19),
('iPhone SE (2020/2022)', 400000, 600000, false, 20);
